Loremipsum = '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis lectus sit amet ante suscipit tempor. Aenean dapibus finibus tortor vitae facilisis. Nulla facilisi. Donec suscipit ante a sapien gravida eleifend. Curabitur in lectus ut enim semper venenatis. Aenean elit nibh, hendrerit nec nunc in, dictum cursus dolor. Aenean eget lectus risus. Cras sollicitudin quam vitae augue mollis bibendum. Aliquam euismod vulputate dolor at tristique. Praesent elementum pretium velit non interdum. Nunc posuere faucibus magna id pretium. Maecenas congue, velit eget semper porttitor, tellus tortor porttitor dui, tristique lobortis quam sem ac odio.

Nam quis ornare diam. Vestibulum mollis varius eros, nec condimentum augue auctor sed. Fusce non efficitur odio. Integer laoreet arcu ornare, malesuada lorem et, luctus lacus. Quisque luctus lacinia urna, ac rutrum ligula gravida sit amet. Integer ligula felis, finibus id quam in, accumsan efficitur mauris. Curabitur sodales ante risus. Aliquam aliquet gravida dolor a porttitor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

In ultrices, dui et pretium laoreet, dui enim pulvinar arcu, et aliquam lorem nunc viverra nunc. Phasellus at arcu nec lectus volutpat sodales vitae ac elit. Ut euismod libero imperdiet, gravida lacus ac, pretium metus. Ut augue lorem, pretium a tempor luctus, varius at enim. Morbi ac tellus rhoncus, porttitor lectus id, maximus arcu. Quisque ex quam, egestas ut fermentum a, vehicula in metus. Nulla aliquam et purus sit amet convallis. Sed et ipsum ante. Curabitur est elit, sollicitudin ut ullamcorper quis, faucibus ac lacus. Sed vitae magna vitae diam malesuada vehicula pretium euismod sapien. Aenean rutrum porttitor consectetur. Pellentesque et volutpat lectus. Donec eget nisi eget odio porta volutpat. Ut quis leo feugiat, auctor quam et, vulputate ante. Vivamus in sodales velit. Praesent felis nisl, commodo ut erat sit amet, fermentum consectetur lacus.

Maecenas viverra vitae erat id pharetra. Ut eget aliquam massa, id rutrum magna. Mauris quis augue non ipsum pulvinar tincidunt eu at ante. Praesent bibendum sem non hendrerit tristique. Vestibulum urna eros, aliquet sit amet faucibus sed, dignissim in eros. Curabitur iaculis, dui ac vehicula ornare, dui augue imperdiet neque, id commodo lacus odio in nibh. Nulla vel dictum ex, vitae suscipit augue. In sem lorem, fringilla eget est at, blandit volutpat enim. Curabitur ac metus odio. Phasellus sed purus id justo iaculis facilisis non ut lectus. Vestibulum sit amet ligula eu dui sagittis varius. Vivamus eleifend orci eu ipsum porta fringilla. Nullam laoreet varius enim ut vulputate.

Aenean fringilla lectus sed justo varius, at venenatis justo gravida. Nullam dictum libero sit amet quam pellentesque, sed porttitor tellus volutpat. Integer rutrum lacus vel dictum consequat. In vitae ipsum facilisis, rhoncus nulla a, molestie mi. Morbi tempus, nibh ac tempor porta, metus elit pulvinar tortor, eu pharetra tortor nulla gravida quam. Praesent rutrum diam purus, cursus porttitor metus pellentesque eu. Etiam et magna elit. Donec id lacinia lacus.

Praesent vel odio quis sapien volutpat consectetur in non magna. Praesent nisl augue, rutrum ut sem eget, aliquam congue enim. Proin maximus, velit sed laoreet euismod, quam lorem porta nibh, a hendrerit mauris felis at nulla. Nam vitae porttitor neque. Sed ac quam nibh. Nullam at erat risus. Maecenas non lectus lobortis, interdum eros vitae, aliquam nibh. Vestibulum rutrum est lacus, vel venenatis orci consectetur et. Suspendisse potenti. Nunc vitae quam vehicula, molestie nulla sed, elementum massa. Aenean sed arcu iaculis, vestibulum elit ac, blandit arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id augue id magna scelerisque vestibulum eu ut tellus. Vestibulum eu erat eu erat ornare iaculis. Phasellus ipsum augue, convallis sed pretium sed, dignissim ut sapien. Etiam lacinia augue commodo, sollicitudin diam vitae, accumsan libero.

Duis vitae justo ac elit tincidunt blandit. Donec eget luctus urna. Nunc tincidunt bibendum lorem, ac fermentum arcu rutrum quis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla facilisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque molestie porta lectus, a accumsan ex dapibus eu. Fusce convallis venenatis gravida. Nam at consectetur tortor. Proin varius lorem id lacinia gravida. Donec a nunc blandit, suscipit dui vitae, tristique neque. Nam a elit tristique, pharetra leo eget, mollis risus. Nam feugiat augue tellus, a commodo tellus pellentesque non. Maecenas elit felis, facilisis nec tempus sit amet, facilisis non sem.

Donec vitae accumsan justo. Pellentesque vel metus tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus ornare ligula quis risus commodo, nec feugiat neque ultricies. Duis eu odio ligula. Duis in posuere leo. Duis placerat hendrerit elit, a rhoncus augue iaculis vulputate.

Quisque eget metus luctus, posuere tortor ultrices, lacinia felis. Curabitur quis est vel velit commodo dictum. Quisque aliquam sit amet turpis quis tempor. Phasellus ac quam et ligula vehicula aliquet a vitae mauris. Curabitur scelerisque, lacus sit amet lobortis consectetur, quam risus fermentum magna, ut imperdiet lacus tellus nec odio. Suspendisse quis quam nec lacus fringilla consectetur. Duis ultricies augue sed suscipit eleifend. Morbi dolor libero, dictum id dignissim vel, laoreet et neque. Phasellus nec leo consectetur, laoreet ligula vitae, hendrerit neque. Ut venenatis vitae purus ac suscipit. Curabitur hendrerit mauris id nisl fermentum, euismod cursus purus dignissim. Nullam et ex sed tortor mattis consectetur. Aenean sit amet volutpat velit.

Cras condimentum euismod lacus. Nulla rhoncus enim faucibus, finibus dui ut, pretium massa. Mauris pulvinar orci risus, et congue nisl cursus eget. Phasellus at euismod libero. Morbi vehicula et ligula id iaculis. Aliquam nulla odio, sodales commodo ligula at, molestie faucibus risus. Sed consectetur tempor justo, vitae condimentum elit pharetra quis. Vivamus tincidunt justo vel bibendum tincidunt. Vivamus eget viverra tellus. Nam dictum dolor nibh, at congue tellus viverra et. Donec felis est, volutpat at nisl quis, pellentesque hendrerit leo.'''.split()
a, b = map(int, input().split())
print(*Loremipsum[a - 1:b])
